# 配置dev环境
spring:
  profiles: dev
  application:
    name: springcloud-provider-config-dev
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://129.28.74.161/vickking?useUnicode=true&characterEncoding=UTF-8
    username: vickking
    password: vickking
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

---

# 配置test环境
spring:
  profiles: dev
  application:
    name: springcloud-provider-config-test
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://129.28.74.161/vickking?useUnicode=true&characterEncoding=UTF-8
    username: vickking
    password: vickking
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
