# 配置dev环境
spring:
  profiles: dev
  application:
    name: springcloud-consumer-config-dev

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

feign:
  hystrix:
    enabled: true

---

# 配置test环境
spring:
  profiles: test
  application:
    name: springcloud-consumer-config-test

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

feign:
  hystrix:
    enabled: true